enable:
  issues: true
  prs: true

comments:
  prs: |
    π” Labelerκ°€ μ λ©κ³Ό μ„¤λ…μ— μ ν€μλ” ν‚¤μ›λ“λ¥Ό λ³΄κ³  Labelμ„ μ μ©ν–μµλ‹λ‹¤.
       μ λ€λ΅ μ μ©λμ—λ”μ§€ ν™•μΈν•΄μ£Όμ„Έμ”.
  issues: |
    π” Labelerκ°€ μ λ©κ³Ό μ„¤λ…μ— μ ν€μλ” ν‚¤μ›λ“λ¥Ό λ³΄κ³  Labelμ„ μ μ©ν–μµλ‹λ‹¤.
       μ λ€λ΅ μ μ©λμ—λ”μ§€ ν™•μΈν•΄μ£Όμ„Έμ”.

labels:
  'bug':
    include:
      - '\bfix\b'
      - '\bbug\b'
  'documentation':
    include:
      - '\bdocs\b'
  'enhancement':
    include:
      - '\bfeat\b'
  'refactor':
    include:
      - '\brefactor\b'
  'chore':
    include:
      - '\bchore\b'
  'help wanted':
    include:
      - '\bhelp\b'
  'question':
    include:
      - '\bquestion\b'
  'test':
    include:
      - '\btest\b'