name: CI Pipeline
run-name: ${{ github.actor }} is currently working on continuous integration 🚀

on:
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy env.properties in test environment
        run: echo "${{ secrets.ENV_PROPERTIES }}" > ./src/test/resources/env.properties

      - name: Set up jdk21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'gradle'

      - name: Test Spring App
        run: ./gradlew build test --no-daemon
